#------------------------------------------指定运行任务列表----------------------------------

#指定运行任务
task_config:
  #指定运行的任务列表
  task_name: task1,task2,task3



#------------------------------------------企微机器人配置列表---------------------------------
#企微机器人配置列表
Robot1:
  RoBot_key: d8aa43ed-319d-429a-9bad-4ef008017eb2

Robot2:
  RoBot_key: d8aa43ed-319d-429a-9bad-4ef008017eb2

Robot3:
  RoBot_key: d8aa43ed-319d-429a-9bad-4ef008017eb2

#------------------------------------------数据库配置列表-----------------------------------

xxl_job:
  host: localhost
  database: xxl_job
  user: root
  password: root


cloud2.0:
  host: localhost
  database: cloud2.0
  user: root
  password: root


flask_demo:
  host: localhost
  database: flask_demo
  user: root
  password: root

#------------------------------------------任务列表----------------------------------------

#任务配置列表

task1:
  #name 为导出excel文件名称
  name: 任务1

  #指定发送消息的机器人
  Robot: Robot1

  #执行 sql 数据库名称
  db: cloud2.0

  #sql 查询语句路径
  sql: ./sql/任务1.sql

  queries:
    - description: "总数量"
      sql_file: ./sql/test_task/总数量.sql
    - description: "成功数量"
      sql_file: ./sql/test_task/成功数量.sql
    - description: "失败数量"
      sql_file: ./sql/test_task/失败数量.sql


  #截止日期
  end_date: 2024-10-24

  # 指定执行日期，多个日期用逗号分隔
  execution_date: 2024-10-09,2024-10-10,2024-10-11


  #------------------------------------------------------------------------------------------

task2:
  #name 为导出excel文件名称
  name: 任务2

  #指定发送消息的机器人
  Robot: Robot2

  #执行 sql 数据库名称
  db: flask_demo

  #sql 查询语句路径
  sql: ./sql/任务2.sql


  #截止日期
  end_date: 2024-10-13


  #------------------------------------------------------------------------------------------

task3:
  #name 为导出excel文件名称
  name: 任务3

  #指定发送消息的机器人
  Robot: Robot3

  #执行 sql 数据库名称
  db: xxl_job

  #sql 查询语句路径
  sql: ./sql/任务3.sql

  #截止日期
  # end_date = 2024-10-08

